server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.198.171.207:2540/canteen?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: master
    password: H@ckath0n